from enum import Enum


class DomainEnum(str, Enum):
    ERP = "ERP"
    ANALYTICS = "ANALYTICS"
    COMMUNICATION = "COMMUNICATION"
    AUTOMATION = "AUTOMATION"
    RETRIEVAL = "RETRIEVAL"
    SUPPORT = "SUPPORT"
    GOVERNANCE = "GOVERNANCE"
    GENERAL = "GENERAL"


class ModuleEnum(str, Enum):
    LEAD_MANAGEMENT = "LEAD_MANAGEMENT"
    CRM = "CRM"
    SALES = "SALES"
    INVENTORY = "INVENTORY"
    FINANCE = "FINANCE"
    EMPLOYEE_MANAGEMENT = "EMPLOYEE_MANAGEMENT"
    ATTENDANCE = "ATTENDANCE"
    PAYROLL = "PAYROLL"
    PROJECTS = "PROJECTS"
    REPORTING = "REPORTING"
    FORECASTING = "FORECASTING"
    KPI_ANALYSIS = "KPI_ANALYSIS"
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    SLACK = "SLACK"
    NOTIFICATIONS = "NOTIFICATIONS"
    TASK_AUTOMATION = "TASK_AUTOMATION"
    APPROVAL_WORKFLOW = "APPROVAL_WORKFLOW"
    SCHEDULER = "SCHEDULER"
    DOCUMENT_SEARCH = "DOCUMENT_SEARCH"
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"
    POLICY_LOOKUP = "POLICY_LOOKUP"
    TICKETING = "TICKETING"
    ESCALATION = "ESCALATION"
    PERMISSIONS = "PERMISSIONS"
    AUDIT = "AUDIT"
    COMPLIANCE = "COMPLIANCE"
    GENERAL = "GENERAL"


class ActionEnum(str, Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    GET = "GET"
    LIST = "LIST"
    ASSIGN = "ASSIGN"
    GENERATE = "GENERATE"
    SEND = "SEND"
    SEARCH = "SEARCH"
    ANALYZE = "ANALYZE"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    ESCALATE = "ESCALATE"
    EXECUTE = "EXECUTE"
    GENERAL = "GENERAL"


class ExecutionTypeEnum(str, Enum):
    SINGLE_TOOL = "SINGLE_TOOL"
    WORKFLOW = "WORKFLOW"
    MULTI_STEP = "MULTI_STEP"
    HUMAN_APPROVAL = "HUMAN_APPROVAL"


class PriorityEnum(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskStatusEnum(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
