from enum import Enum


class IntentEnum(str, Enum):
    ERP_OPERATION = "ERP_OPERATION"
    SUPPORT_OPERATION = "SUPPORT_OPERATION"
    AUTOMATION_OPERATION = "AUTOMATION_OPERATION"
    GENERAL_QUERY = "GENERAL_QUERY"